# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BeiO1tEJc3M3zt7VLN_cvPClC8CZp6Za
"""
import streamlit as st
import pickle

# Model loaded 
model = pickle.load(open("model.pkl", "rb"))
scaler = pickle.load(open("scaler.pkl", "rb"))
le = pickle.load(open("label.pkl", "rb"))

st.set_page_config(page_title="Crop Recommendation", layout="centered")

st.title("Crop Recommendation App")
st.subheader("Enter  Details")

#'N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall'

N= st.number_input("Nitrogen")
P=st.number_input("phosphorus")
K= st.number_input("Pottasium")
temp= st.number_input("Temprature")
hum= st.number_input("Humidity")
ph= st.number_input("ph level")
rain= st.number_input("rainfall")

if st.button(" Predict crop"):
    input_data = [[N,P,K,temp,hum,ph,rain]]
    input_scaled = scaler.transform(input_data)
    prediction = model.predict(input_scaled)
    crop = le.inverse_transform(prediction)

    st.success(f" Recommended Crop: **{crop[0]}**")
